# Generated by Django 4.0.4 on 2022-05-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xasify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='price',
            field=models.IntegerField(default=0, help_text='Precio de venta del producto', verbose_name='Product.price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(help_text='Costo del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Precio de ventana del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(help_text='Unidades del producto'),
        ),
    ]
