# Generated by Django 4.0.4 on 2022-05-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xasify', '0002_sell_price_alter_product_cost_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='price',
        ),
    ]
