# Generated by Django 4.0.4 on 2022-05-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xasify', '0005_product_utility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='utility',
        ),
    ]
