# Generated by Django 4.0.4 on 2022-05-15 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xasify', '0008_alter_product_options_alter_sell_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['dataTime']},
        ),
        migrations.AlterField(
            model_name='sell',
            name='dataTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='xasify.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
