# Generated by Django 4.0.4 on 2022-05-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xasify', '0009_alter_sell_options_alter_sell_datatime_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='products',
        ),
        migrations.AddField(
            model_name='seller',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xasify.product'),
        ),
    ]
