# Generated by Django 4.0.4 on 2022-05-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xasify', '0010_remove_seller_products_seller_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
