# Generated by Django 4.0.4 on 2022-05-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xasify', '0012_sell_costo_de_producto_sell_precio_de_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='costo_de_producto',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='precio_de_venta',
        ),
    ]
