# Generated by Django 4.0.4 on 2022-05-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xasify', '0013_remove_sell_costo_de_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
