# Generated by Django 4.0.4 on 2022-05-15 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xasify', '0014_remove_product_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sell',
            new_name='Sales',
        ),
    ]
