# Generated by Django 4.0.4 on 2022-05-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xasify', '0016_alter_sales_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to='xasify.product'),
        ),
    ]
